// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDylUdt1p0OkdX_Ldsii2RfPdTyb277y4o',
    appId: '1:342382169586:web:c420b83eb040d55e476f6b',
    messagingSenderId: '342382169586',
    projectId: 'flash-chat-2ba82',
    authDomain: 'flash-chat-2ba82.firebaseapp.com',
    storageBucket: 'flash-chat-2ba82.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgbgtmCD4McWXuekRN9X8ateMRP_NJNjg',
    appId: '1:342382169586:android:093e505ab5e12d1e476f6b',
    messagingSenderId: '342382169586',
    projectId: 'flash-chat-2ba82',
    storageBucket: 'flash-chat-2ba82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBv_3A2NM2PZapYYwsT6sjhAiHSyNFVt4',
    appId: '1:342382169586:ios:e4632f9be459131e476f6b',
    messagingSenderId: '342382169586',
    projectId: 'flash-chat-2ba82',
    storageBucket: 'flash-chat-2ba82.appspot.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBv_3A2NM2PZapYYwsT6sjhAiHSyNFVt4',
    appId: '1:342382169586:ios:e4632f9be459131e476f6b',
    messagingSenderId: '342382169586',
    projectId: 'flash-chat-2ba82',
    storageBucket: 'flash-chat-2ba82.appspot.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDylUdt1p0OkdX_Ldsii2RfPdTyb277y4o',
    appId: '1:342382169586:web:3e11a76579f54e00476f6b',
    messagingSenderId: '342382169586',
    projectId: 'flash-chat-2ba82',
    authDomain: 'flash-chat-2ba82.firebaseapp.com',
    storageBucket: 'flash-chat-2ba82.appspot.com',
  );
}
